# Generated by Django 4.1.6 on 2023-07-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='тема сообщения')),
                ('body', models.TextField(verbose_name='тело сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='время рассылки')),
                ('period', models.CharField(choices=[('day', 'день'), ('week', 'неделя'), ('month', 'месяц')], default='day', max_length=15, verbose_name='периодичность расссылки')),
                ('status', models.CharField(choices=[('created', 'создана'), ('launched', 'запущена'), ('completed', 'завершена')], default='created', max_length=15, verbose_name='статус рассылки')),
                ('addresses_spam', models.ManyToManyField(to='mailing_app.client', verbose_name='адреса для рассылок')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройка рассылок',
            },
        ),
        migrations.CreateModel(
            name='AttemptMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt_date_time', models.DateTimeField(verbose_name='дата и время последней попытки рассылки')),
                ('status', models.CharField(choices=[('delivered', 'доставлено'), ('not_delivered', 'не доставлено')], default='delivered', max_length=15, verbose_name='статус')),
                ('server_response', models.CharField(blank=True, max_length=100, verbose_name='ответ сервера, если он был')),
                ('settings_pk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.settings')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
            },
        ),
    ]
