# Generated by Django 4.1.6 on 2023-07-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptmailing',
            name='last_attempt_date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки рассылки'),
        ),
    ]
