"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os.path
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

BASE_URL = os.getenv('BASE_URL')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'mailing_app',
    'django_crontab',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {  # работает, но когда все насройки указаны, но не с суперпользователя базаданных
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',  # ругается на psycopg2, надо 'django.db.backends.postgresql_psycopg2'
#         'NAME': 'django_1',  # базу надо создать БЕЗ КОВЫЧЕК, иначе не будет работать!
#         'USER': 'django',
#
#         'HOST': 'localhost',  #
#         'PORT': 5432,  #
#         'PASSWORD': 'password',  #
#
#     }
# }

DATABASES = {  # но так не хочет работать, если на полную ставить заполнение. надо убрать host, post, password
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # ругается на psycopg2, надо 'django.db.backends.postgresql_psycopg2'
        'NAME': 'django_course_work_1',  # базу надо создать БЕЗ КОВЫЧЕК, иначе не будет работать!
        'USER': 'postgres',

        # 'HOST': 'localhost',  # с только за коменченным локалхостом работает, так же работает если лишнее тоже убрать
        # 'PORT': 5432,  #
        # 'PASSWORD': 12345,  #

    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = (
    BASE_DIR / 'static',
)

MEDIA_ROOT = BASE_DIR / 'media/'  # путь к медиа(от корня) физический
MEDIA_URL = '/media/'  # путь к медиа, виртуальный, когда на сервер придёт запрос, т.е. будет туда заходить и искать что нам надо

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER') # КАКОЙ-ТО ящик, либо личный, либо тестовый
# EMAIL_HOST_USER = None
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# EMAIL_HOST_PASSWORD = None
EMAIL_USE_SSL = True  # ЗНАЧИТ, ЧТО наш бекенд будет общаться с безопасным соединением и с ним  работать

# AUTH_USER_MODEL = 'users.User'  # это ссылка на приложения, а потом дальше на модель из этого приложения.
# LOGIN_URL = '/users/'
# LOGIN_REDIRECT_URL = '/'
# LOGOUT_REDIRECT_URL = '/'
#
CACHE_ENABLED = os.getenv('CACHE_ENABLED')

if CACHE_ENABLED:
    CASHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': 'redis://127.0.0.1:6379',
            # 'TIMEOUT': 300, # это сколько хранится кэш, 300 секунд по умолчанию
        }
    }


CRONJOBS = [
    ('*/1 * * * *', 'mailing_app.sup_service.test_send_mail'),
    ('*/1 * * * *', 'mailing_app.cron_test.add_rand_client'),
]